### ISSUE TITLE
Ceres solver instead of Mosek?

### ISSUE THREAD

**Issue by FaboNo** [HKUST-Aerial-Robotics/Btraj#4]
Greatwork actually and I would like to ask you why did you choose Mosek to solve the quadratic optimization problem? It can be solved using Ceres solver as well no?
Thank you

**Comment by USTfgaoaa** [comment]
@FaboNo 
Hi Fabo, of course, you can use it. Since the trajectory generation in this work is indeed a convex QP problem, optimize it numerically (such as using ceres, nlopt ...)  can also obtain a global optimal result.

The reason why I use MOSEK is that it can solve such 'standard' convex problems very efficiently (much more efficient than optimize it numerically) and this problem is 'standard'. Usually, 'standard' convex problems includes QP, LP, SOCP, SDP, etc.
